### ISSUE TITLE
link Broken

### ISSUE THREAD

**Issue by brdalert** [sgsax/sgbot#1]
the link to the homer Simpson doh sound no longer works

**Comment by sgsax** [comment]
Suggest a replacement

**Comment by brdalert** [comment]
https://www.youtube.com/watch?v=F3k_BfQFrUo

**Comment by brdalert** [comment]
or http://www.wavsource.com/snds_2017-07-30_6786517629734627/tv/simpsons/homer/doh1_y.wav

**Comment by sgsax** [comment]
got it, thanks
